services:
  pythshare:
    container_name: pythshare
    image: bluemethyst/pythshare:1.0.0
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - /srv/docker/pythshare/uploads:/app/uploads